In [1]:
import numpy as np

In [6]:
x = np.linspace(1,100,10)
cd = x[1]-x[0]

print(x)

print(cd)
print(np.sum(x))
s1 = len(x) * (x[0]*(x[9]))/2

[   1.   12.   23.   34.   45.   56.   67.   78.   89.  100.]
11.0
505.0


In [9]:
x = np.linspace(1,10,10)
y = np.linspace(1,10,10)
z = sorted(y, reverse=True)

print(x+z)
print(np.sum(x+z)/2)

[ 11.  11.  11.  11.  11.  11.  11.  11.  11.  11.]
55.0


In [10]:
a = 1
d = 1
n = 10

s1 = n*(a+(a*d*n))/2
print(s1)
s = (n*(2*a+(n-1)*d))/2
print(s)

55.0
55.0


In [11]:
x = np.ones(10)
print(x)
n = np.linspace(1,10,10)
r = 2**n
y = x*r
print(y)
print("common ration", y[1]/y[0])

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]
common ration 2.0


In [12]:
cr = y[1]/y[0]
print(cr)
a = y[0]
print(a)
nn = len(n)
print(nn)

zz = (a*(1-cr**nn))/(1-cr)
print(zz)

2.0
2.0
10
2046.0
